version: !!str 3

services:
  minio:
    image: minio/minio
    restart: unless-stopped
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
        

